### ISSUE TITLE
Width is not being set to Size I provided via props for resizable spaces

### ISSUE THREAD

**Issue by thekapadia** [aeagle/react-spaces#29] opened 2019-10-09 05:48 UTC
@aeagle I'm facing this problem.

Step 1: I initially have,
`<Left resizable={true} size={200}> Left Section </Left>`

Step 2: Now on click of a button, I'm manually toggling the `size` prop between 10 and 200. All works well.

Step 3: Now I resize this space by dragging it, thus, let's say, increasing the size by 20.

Step 4: I repeat Step 2. This is where the problem occurs. The calculated width becomes `calc(30px)` and `calc(220px)`. Somehow the resized delta is being added to the size I'm providing.

**Comment by aeagle** [comment] 2019-10-09 10:13
@thekapadia Looks like a problem with the resize delta not being reset in state for a space when the size prop is changed. I'll have a proper look and hopefully have a fix shortly.

**Comment by thekapadia** [comment] 2019-10-16 03:00
Hi @aeagle - just checking in to see if there's any update on this issue.

**Comment by aeagle** [comment] 2019-10-16 08:22
@thekapadia - I'm nearly there with a fix: https://github.com/aeagle/react-spaces/commit/bdfe5767cafce07c8ab778ce30000563e0ccb001 

However there seems to be some strange behavior when testing with spaces that are stacked. Once I get this resolved I will release. Hopefully not much longer.

**Comment by aeagle** [comment] 2019-10-17 21:21
@thekapadia I've published a fix for this in version 0.1.17. Let me know if this resolves your issue.

**Comment by Slapbox** [comment] 2019-10-18 18:34
@aeagle I'm realizing my issue #36 is an exact duplicate of this one.

I tried `0.1.17` yesterday thinking also that one of your commits looked likely to resolve the issue before realizing what was going on and updating my issue.

**Closed** 2019-10-21 21:32 UTC
Labels: bug
