### ISSUE TITLE
Cannot update a component ... while rendering a different component in React 16.13.1 - 2.0 beta issue

### ISSUE THREAD

**Issue by ttungbmt** [aeagle/react-spaces#75] opened 2020-09-29 08:35 UTC
**Describe the bug**
In React 16.13.1, I have an error when rendering component

Warning: Cannot update a component (`Fixed`) while rendering a different component (`Unknown`). To locate the bad setState() call inside `Unknown`, follow the stack trace as described in https://fb.me/setstate-in-render

**Comment by aeagle** [comment] 2020-09-29 15:15
This is most likely a duplicate of #64. The warning message from React could have changed slightly between versions 16.13.0 and 16.13.1. I am currently working on a new version which is quite a major refactor which removes this problem. You could try out version v0.2.0-beta.2 to see if this resolves the issue. Note this is a beta version and still in progress.

**Comment by luskin** [comment] 2020-11-11 19:53
any update on this?

**Comment by aeagle** [comment] 2020-11-12 08:46
Hi @luskin have you tried the beta version mentioned in the comment above?

**Comment by fdelbos** [comment] 2020-12-05 00:51
Hi @aeagle, i just tried with v0.2.0-beta.2 and still go the same problem.

**Comment by aeagle** [comment] 2020-12-06 00:05
Hi @fdelbos,

I've tried to recreate this but do not have the same issue. Here is the sandbox I setup using the same version of React and of React Spaces - https://codesandbox.io/s/zealous-clarke-k89cu?file=/src/App.js

The console is clear for me.

Could you send a sandbox reproducing the issue?

**Comment by aeagle** [comment] 2020-12-10 20:49
Feel free to reopen if you can provide a repro with React `v16.13.1` and version `v0.2.0-beta.5`

**Closed by aeagle** 2020-12-10 20:49 UTC
Labels: bug v2.0, v0.2.0
